name: py39_spacy_cpu     # Name of the created environment
channels:                # Repositories to search for packages
- conda-forge
dependencies:            # List of packages that should be installed
- python=3.9             # Python
- py4j                   # used for KNIME <-> Python communication
- nomkl                  # Prevents the use of Intel's MKL !!! Can't install pytorch with conda if nomkl is present !!! MKL doesn't work at all on Mac M1
- pandas                 # Table data structures
- numpy                  # N-dimensional arrays
- pyarrow<8.0                # Arrow serialization
- pip
- pip:
  - torch==1.12.1               # needed by spacy-transformers
  - spacy==3.4.1
  - spacy-transformers==1.1.7   # needed for models using transformers
