name: py39_spacy_cpu     # Name of the created environment
channels:                # Repositories to search for packages
- conda-forge
dependencies:            # List of packages that should be installed
- python=3.9             # Python
- py4j                   # used for KNIME <-> Python communication
- pandas                 # Table data structures
- numpy                  # N-dimensional arrays
- pyarrow<8.0            # Arrow serialization
- tokenizers=0.12.1      # Needed by spacy
- spacy=3.4.1
- pytorch=1.12.1
- spacy-transformers=1.1.8