name: py39_spacy_gpu     # Name of the created environment
channels:                # Repositories to search for packages
- conda-forge
dependencies:            # List of packages that should be installed
- python=3.9             # Python
- py4j                   # used for KNIME <-> Python communication
- nomkl                  # Prevents the use of Intel's MKL
- pandas                 # Table data structures
- numpy                  # N-dimensional arrays
- pyarrow<8.0            # Arrow serialization
- tokenizers=0.12.1      # Needed by spacy
- spacy-pkuseg<0.1.0     # Needed by chinese models
- cudatoolkit=11.6
- cupy=11.0
- pip
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu116
  - torch==1.12.1                # needed by spacy-transformers
  - spacy==3.5.3
  - spacy-transformers==1.1.7   # needed for models using transformers
  - pymorphy2              # Needed by russian models
  - pymorphy3              # Needed by russian models
  - pymorphy3-dicts-uk     # Needed by ukrainian models
  - sudachipy              # Needed by japanese models
  - sudachidict-core       # Needed by japanese models
